### ISSUE TITLE
`porffor@latest` on NPM crashing

### ISSUE THREAD

**Issue by notramo** [CanadaHonk/porffor#216]
```
$ bun x porffor@latest native hello.ts hello
243 |     outFile ??= Prefs.native ? './porffor_tmp' : file.split('/').at(-1).split('.')[0
          ^
error: This assignment will throw because "outFile" is a constant
    at /tmp/bunx-1000-porffor@latest/node_modules/porffor/compiler/index.js:243:5

70 |   const outFile = Prefs.o;
             ^
note: The symbol "outFile" was declared a constant here:
   at /tmp/bunx-1000-porffor@latest/node_modules/porffor/compiler/index.js:70:9

Bun v1.1.39-canary.112+1fa0dee5e (Linux x64 baseline)
```

It also happens with Node and `pnpx`. The error message is differently phrased, but it's the same error (assignment to a constant).

The program file content doesn't affect the error.

**Comment by CanadaHonk** [comment]
Whoops, thanks for the report, fixed!
